const MenuCardList = [
	{
		id: 1,
		type: 'Rolls',
		name: 'Alaska',
		price: 2,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_40/5cc696e97d70c-450x450.jpg',
		composition: 'Salmon, cream cheese, cucumber, sesame, rice, nori',
		proteins: 10,
		greases: 8,
		carbohydrates: 18,
		calories: 195,
		pieces: 4,
		weight: '32 gr/roll',
	},
	{
		id: 2,
		type: 'Rolls',
		name: 'California',
		price: 3,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_46/5f15654d23d00-450x450.jpg',
		composition:
			'Masago caviar, crab imitation, cream cheese, cucumber, rice, nori',
		proteins: 6,
		greases: 5,
		carbohydrates: 20,
		calories: 154,
		pieces: 4,
		weight: '35 gr/roll',
	},
	{
		id: 3,
		name: 'Lava (Spicy)',
		type: 'Rolls',
		price: 4,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_50/5cc697f9680c7-450x450.jpg',
		composition:
			'Salmon, cream cheese, crab, cucumber, spicy sauce, rice, nori',
		proteins: 14,
		greases: 5,
		carbohydrates: 43,
		calories: 225,
		pieces: 4,
		weight: '40 gr/roll',
	},
	{
		id: 4,
		name: 'Dragon light',
		type: 'Rolls',
		price: 3,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_45/5cc6977f057ef-450x450.jpg',
		composition:
			'Eel, cream cheese, takuan, Masago caviar, sesame seeds, unagi sauce, rice, nori',
		proteins: 9,
		greases: 11,
		carbohydrates: 23,
		calories: 233,
		pieces: 4,
		weight: '33 gr/roll',
	},
	{
		id: 5,
		name: 'Boston',
		type: 'Rolls',
		price: 3,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_43/5cc69713b43c8-450x450.jpg',
		composition: 'Shrimp, Masago caviar, cream cheese, cucumber, rice, nori',
		proteins: 18,
		greases: 5,
		carbohydrates: 42,
		calories: 234,
		pieces: 4,
		weight: '33 gr/roll',
	},
	{
		id: 6,
		name: 'bonsai',
		type: 'Rolls',
		price: 3,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_41/5cc696f673797-450x450.jpg',
		composition: 'Bacon, cream cheese, cucumber, sesame, rice, nori',
		proteins: 7,
		greases: 11,
		carbohydrates: 19,
		calories: 208,
		pieces: 4,
		weight: '33 gr/roll',
	},
	{
		id: 7,
		name: 'Seaman',
		type: 'Rolls',
		price: 5,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_415/5cc69841140b2-450x450.jpg',
		composition:
			'Lightly salted salmon, cream cheese, tuna, masago caviar, rice, nori',
		proteins: 6,
		greases: 10,
		carbohydrates: 11,
		calories: 156,
		pieces: 4,
		weight: '35 gr/roll',
	},
	{
		id: 8,
		name: 'Philadelphia',
		type: 'Rolls',
		price: 3,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_55/5cc698e644aa9-450x450.jpg',
		composition: 'Lightly salted salmon, cream cheese, rice, nori',
		proteins: 11,
		greases: 9,
		carbohydrates: 17,
		calories: 204,
		pieces: 4,
		weight: '32 gr/roll',
	},
	{
		id: 9,
		name: 'Friday',
		type: 'Sets',
		price: 22,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_1132/60669639a204f-450x450.jpg',
		composition:
			'Philadelphia (5 pcs.), Philadelphia light (5 pcs.), Yasai Maki (5 pcs.), Utah (5 pcs.), Bansai (5 pcs.), Boston (5 pcs.), California (5 pcs.) , Wasabi (2 pcs.), Ginger (2 pcs.), Soy sauce (2 pcs.)',
		proteins: 8,
		greases: 10,
		carbohydrates: 23,
		calories: 222,
		pieces: 20,
		weight: '1.13 kg',
	},
	{
		id: 10,
		name: 'Shok',
		type: 'Sets',
		price: 26,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_1280/61403c52b2eed-450x450.jpg',
		composition:
			'Roll with salmon and hat (5 pcs.), Roll with cheese (5 pcs.), Roll with salmon (5 pcs.), Roll with bacon (5 pcs.), Roll with crab (5 pcs.), Roll with shrimp (5 pcs.), Takuan roll (5 pcs.), Kappa maki (8 pcs.)',
		proteins: 9,
		greases: 2,
		carbohydrates: 6,
		calories: 297,
		pieces: 43,
		weight: '1.27 kg',
	},
	{
		id: 11,
		name: 'Legend',
		type: 'Sets',
		price: 155,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_100/606695c38cb23-450x450.jpg',
		composition:
			'Philadelphia (6pcs), California (25pcs), Yasai (18pcs), Bansai (20pcs), Akira (20pcs), Lava (20pcs), Syake Maki (16pcs), Nagai (10 pcs.), Boston (10 pcs.), Philadelphia with cucumber (10 pcs.), California luxury (20 pcs.), Naples (20 pcs.), Casablanca (10 pcs.), Palermo (10 pcs.), Alaska (10 pcs.), Philadelphia deluxe (5 pcs.), Hawaii (10 pcs.), large container (8 pcs.), small container (1 pcs.)',
		proteins: 11,
		greases: 7,
		carbohydrates: 24,
		calories: 203,
		pieces: 240,
		weight: '7.95 kg',
	},
	{
		id: 12,
		name: 'SENSEI',
		type: 'Hot Rolls',
		price: 5,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_35/5cc6c4e17c9df-450x450.jpg',
		composition:
			'Lightly salted salmon, cream cheese, masago caviar, spicy sauce, rice, nori, in Panko croutons',
		proteins: 10,
		greases: 10,
		carbohydrates: 12,
		calories: 184,
		pieces: 5,
		weight: '32 gr/roll',
	},
	{
		id: 13,
		name: 'TEMPURA TUNA',
		type: 'Hot Rolls',
		price: 4,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_33/5cc6c5da09cbc-450x450.jpg',
		composition:
			'Tuna, cream cheese, spicy sauce, rice, nori, in Panko croutons',
		proteins: 10,
		greases: 9,
		carbohydrates: 13,
		calories: 176,
		pieces: 5,
		weight: '32 gr/roll',
	},
	{
		id: 14,
		name: 'TEMPURA canada',
		type: 'Hot Rolls',
		price: 4,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_34/5cc6c593779f4-450x450.jpg',
		composition:
			'Lightly salted salmon, cream cheese, fresh cucumber, rice, nori, in Panko croutons',
		proteins: 9,
		greases: 5,
		carbohydrates: 22,
		calories: 175,
		pieces: 5,
		weight: '32 gr/roll',
	},
	{
		id: 15,
		name: 'CHUKA SALAD',
		type: 'Salads',
		price: 8,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_78/5cc696bc9ad5e-450x450.jpg',
		composition: 'Chuka salad, sesame sauce',
		proteins: 1,
		greases: 8,
		carbohydrates: 11,
		calories: 123,
		pieces: 1,
		weight: '150 gr',
	},
	{
		id: 16,
		name: 'WATER 0.33',
		type: 'Drinks',
		price: 1,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_853/5efea90d8d382-450x450.jpg',
		composition: 'Water',
		proteins: 0,
		greases: 0,
		carbohydrates: 0,
		calories: 0,
		pieces: 1,
		weight: '0.33 L',
	},
	{
		id: 17,
		name: 'MORS CRANBERRY',
		type: 'Drinks',
		price: 2,
		imageUrl:
			'https://storage.yandexcloud.net/sushi-market/products/product_1315/6152b158dd677-450x450.jpg',
		composition: 'Water',
		proteins: 0,
		greases: 0,
		carbohydrates: 0,
		calories: 0,
		pieces: 1,
		weight: '0.33 L',
	},
];

export default MenuCardList;
